DROP TABLE IF exists KART_ADMIN;
DROP TABLE IF exists KART_COMMERCIAL;
DROP TABLE IF exists KART_COMPANY;

CREATE TABLE KART_ADMIN (
    ID VARCHAR(255) NOT NULL,
    CREATION_TIME DATETIME NOT NULL,
    ENABLED BOOLEAN NOT NULL,
    LAST_LOGIN_TIME DATETIME,
    PASSWORD VARCHAR(255) NOT NULL,
    ROLE VARCHAR(255) NOT NULL,
    USERNAME VARCHAR(255),
    EMAIL VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID)
);

ALTER TABLE KART_ADMIN ADD CONSTRAINT UK_ADMIN_USERNAME UNIQUE (USERNAME);

CREATE TABLE KART_COMPANY (
    ID VARCHAR(255) NOT NULL,
    CREATION_TIME DATETIME NOT NULL,
    ENABLED BOOLEAN NOT NULL,
    LAST_LOGIN_TIME DATETIME,
    PASSWORD VARCHAR(255) NOT NULL,
    ROLE VARCHAR(255) NOT NULL,
    USERNAME VARCHAR(255),
    EMAIL VARCHAR(255) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    PHONE VARCHAR(255) NOT NULL,
    VAT VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID)
);

ALTER TABLE KART_COMPANY ADD CONSTRAINT UK_COMPANY_USERNAME UNIQUE (USERNAME);

CREATE TABLE KART_COMMERCIAL (
    ID VARCHAR(255) NOT NULL,
    CREATION_TIME DATETIME NOT NULL,
    ENABLED BOOLEAN NOT NULL,
    LAST_LOGIN_TIME DATETIME,
    PASSWORD VARCHAR(255) NOT NULL,
    ROLE VARCHAR(255) NOT NULL,
    USERNAME VARCHAR(255),
    EMAIL VARCHAR(255) NOT NULL,
    FIRSTNAME VARCHAR(255) NOT NULL,
    LASTNAME VARCHAR(255) NOT NULL,
    PHONE VARCHAR(255) NOT NULL,
    COMPANY_ID VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID)
);

ALTER TABLE KART_COMMERCIAL ADD CONSTRAINT UK_COMMERCIAL_USERNAME UNIQUE (USERNAME);
ALTER TABLE KART_COMMERCIAL ADD CONSTRAINT FK_COMMERCIAL_COMPANY FOREIGN KEY (COMPANY_ID) REFERENCES KART_COMPANY (ID);

INSERT INTO KART_ADMIN (CREATION_TIME, ENABLED, LAST_LOGIN_TIME, PASSWORD, ROLE, USERNAME, EMAIL, ID) values (CURRENT_TIMESTAMP(), 1, NULL, '{noop}admin', 'ROLE_ADMIN', 'admin', 'admin@kart.com', '58efc5f0-155f-4d1c-9c38-634fade763ba')